services:
  psql_users:
    image: postgres:latest
    container_name: psql_users
    ports:
      - "5433:5432"
    networks:
      - work_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: usersconnector
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - uc_volume_users:/var/lib/postgresql/data

  mongo_cont:
    image: mongo:latest
    container_name: mongo_cont
    ports:
      - "27000:27017"
    networks:
      - work_net
    volumes:
      - mongo_data:/data/db

  users_service:
    build:
      context: ./UsersService
    container_name: UsersService
    ports:
      - "6000:50051"
    networks:
      - work_net
    environment:
      - DB_CONN_STR=postgres://postgres:123@psql_users:5432/usersconnector?sslmode=disable

    depends_on:
      psql_users:
        condition: service_healthy

  api-gateway:
    build: 
      context: ./API-Gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    networks:
      - work_net
    depends_on:
      - users_service
    environment:
      - HOST=UsersService
      - PORT=50051

networks:
  work_net:

volumes:
  uc_volume_users:
  mongo_data: